# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from math import sin,cos,tan,log,exp,pi,e
import qdarkgraystyle
class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.setWindowModality(QtCore.Qt.WindowModal)
        Frame.resize(358, 325)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Light")
        font.setBold(True)
        font.setItalic(True)
        Frame.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Frame)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Operation = QtWidgets.QLineEdit(self.centralwidget)
        self.Operation.setEnabled(False)
        self.Operation.setObjectName("Operation")
        self.horizontalLayout_2.addWidget(self.Operation)
        self.Evaluate = QtWidgets.QPushButton(self.centralwidget)
        self.Evaluate.setObjectName("Evaluate")
        self.horizontalLayout_2.addWidget(self.Evaluate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(0, 12, 0, 12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Divide = QtWidgets.QPushButton(self.centralwidget)
        self.Divide.setObjectName("Divide")
        self.gridLayout_2.addWidget(self.Divide, 2, 3, 1, 1)
        self.Clear = QtWidgets.QPushButton(self.centralwidget)
        self.Clear.setObjectName("Clear")
        self.gridLayout_2.addWidget(self.Clear, 2, 0, 1, 1)
        self.Multiply = QtWidgets.QPushButton(self.centralwidget)
        self.Multiply.setObjectName("Multiply")
        self.gridLayout_2.addWidget(self.Multiply, 3, 3, 1, 1)
        self.Nine = QtWidgets.QPushButton(self.centralwidget)
        self.Nine.setObjectName("Nine")
        self.gridLayout_2.addWidget(self.Nine, 6, 2, 1, 1)
        self.Exp = QtWidgets.QPushButton(self.centralwidget)
        self.Exp.setObjectName("Exp")
        self.Exp.hide()
        self.gridLayout_2.addWidget(self.Exp, 1, 3, 1, 1)
        self.Six = QtWidgets.QPushButton(self.centralwidget)
        self.Six.setObjectName("Six")
        self.gridLayout_2.addWidget(self.Six, 5, 2, 1, 1)
        self.Sign = QtWidgets.QPushButton(self.centralwidget)
        self.Sign.setObjectName("Sign")
        self.gridLayout_2.addWidget(self.Sign, 2, 1, 1, 1)
        self.Substract = QtWidgets.QPushButton(self.centralwidget)
        self.Substract.setObjectName("Substract")
        self.gridLayout_2.addWidget(self.Substract, 5, 3, 1, 1)
        self.Delete = QtWidgets.QPushButton(self.centralwidget)
        self.Delete.setObjectName("Delete")
        self.gridLayout_2.addWidget(self.Delete, 2, 2, 1, 1)
        self.Seven = QtWidgets.QPushButton(self.centralwidget)
        self.Seven.setObjectName("Seven")
        self.gridLayout_2.addWidget(self.Seven, 6, 0, 1, 1)
        self.Sin = QtWidgets.QPushButton(self.centralwidget)
        self.Sin.setObjectName("Sin")
        self.Sin.hide()
        self.gridLayout_2.addWidget(self.Sin, 1, 1, 1, 1)
        self.Eight = QtWidgets.QPushButton(self.centralwidget)
        self.Eight.setObjectName("Eight")
        self.gridLayout_2.addWidget(self.Eight, 6, 1, 1, 1)
        self.Two = QtWidgets.QPushButton(self.centralwidget)
        self.Two.setObjectName("Two")
        self.gridLayout_2.addWidget(self.Two, 3, 1, 1, 1)
        self.Three = QtWidgets.QPushButton(self.centralwidget)
        self.Three.setObjectName("Three")
        self.gridLayout_2.addWidget(self.Three, 3, 2, 1, 1)
        self.Five = QtWidgets.QPushButton(self.centralwidget)
        self.Five.setObjectName("Five")
        self.gridLayout_2.addWidget(self.Five, 5, 1, 1, 1)
        self.Add = QtWidgets.QPushButton(self.centralwidget)
        self.Add.setObjectName("Add")
        self.gridLayout_2.addWidget(self.Add, 6, 3, 1, 1)
        self.Four = QtWidgets.QPushButton(self.centralwidget)
        self.Four.setObjectName("Four")
        self.gridLayout_2.addWidget(self.Four, 5, 0, 1, 1)
        self.Tan = QtWidgets.QPushButton(self.centralwidget)
        self.Tan.setObjectName("Tan")
        self.Tan.hide()
        self.gridLayout_2.addWidget(self.Tan, 1, 2, 1, 1)
        self.Cos = QtWidgets.QPushButton(self.centralwidget)
        self.Cos.setObjectName("Cos")
        self.Cos.hide()
        self.gridLayout_2.addWidget(self.Cos, 1, 0, 1, 1)
        self.One = QtWidgets.QPushButton(self.centralwidget)
        self.One.setObjectName("One")
        self.gridLayout_2.addWidget(self.One, 3, 0, 1, 1)
        self.Ln = QtWidgets.QPushButton(self.centralwidget)
        self.Ln.setObjectName("Ln")
        self.Ln.hide()
        self.gridLayout_2.addWidget(self.Ln, 0, 0, 1, 1)
        self.Euler = QtWidgets.QPushButton(self.centralwidget)
        self.Euler.setObjectName("Euler")
        self.Euler.hide()
        self.gridLayout_2.addWidget(self.Euler, 0, 1, 1, 1)
        self.Pi = QtWidgets.QPushButton(self.centralwidget)
        self.Pi.setObjectName("Pi")
        self.Pi.hide()
        self.gridLayout_2.addWidget(self.Pi, 0, 2, 1, 1)
        self.Exponent = QtWidgets.QPushButton(self.centralwidget)
        self.Exponent.setObjectName("Exponent")
        self.Exponent.hide()
        self.gridLayout_2.addWidget(self.Exponent, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Zero = QtWidgets.QPushButton(self.centralwidget)
        self.Zero.setObjectName("Zero")
        self.horizontalLayout_3.addWidget(self.Zero)
        self.Point = QtWidgets.QPushButton(self.centralwidget)
        self.Point.setObjectName("Point")
        self.horizontalLayout_3.addWidget(self.Point)
        self.More = QtWidgets.QPushButton(self.centralwidget)
        self.More.setObjectName("More")
        self.horizontalLayout_3.addWidget(self.More)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        Frame.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Frame)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 358, 21))
        self.menubar.setObjectName("menubar")
        Frame.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Frame)
        self.statusbar.setObjectName("statusbar")
        Frame.setStatusBar(self.statusbar)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)



        self.Evaluate.clicked.connect(self.func_Evaluate)
        self.Clear.clicked.connect(self.func_Clear)
        self.Sign.clicked.connect(self.func_Sign)
        self.Delete.clicked.connect(self.func_Delete)
        self.Divide.clicked.connect(self.func_Divide)
        self.One.clicked.connect(self.func_One)
        self.Two.clicked.connect(self.func_Two)
        self.Three.clicked.connect(self.func_Three)
        self.Four.clicked.connect(self.func_Four)
        self.Five.clicked.connect(self.func_Five)
        self.Six.clicked.connect(self.func_Six)
        self.Seven.clicked.connect(self.func_Seven)
        self.Eight.clicked.connect(self.func_Eight)
        self.Nine.clicked.connect(self.func_Nine)
        self.Zero.clicked.connect(self.func_Zero)
        self.Point.clicked.connect(self.func_Point)
        self.More.clicked.connect(self.func_More)
        self.Add.clicked.connect(self.func_Add)
        self.Multiply.clicked.connect(self.func_Multiply)
        self.Substract.clicked.connect(self.func_Substract)
        self.Cos.clicked.connect(self.func_Cos)
        self.Sin.clicked.connect(self.func_Sin)
        self.Tan.clicked.connect(self.func_Tan)
        self.Ln.clicked.connect(self.func_Ln)
        self.Exp.clicked.connect(self.func_Exp)
        self.Exponent.clicked.connect(self.func_Exponent)
        self.Euler.clicked.connect(self.func_Euler)
        self.Pi.clicked.connect(self.func_Pi)
        self.centralwidget.setStyleSheet(qdarkgraystyle.load_stylesheet())

    def func_Evaluate(self):
        self.Operation.setText(str(eval(self.Operation.text())))
    def func_Clear(self):
        self.Operation.setText(" ")

    def func_Sign(self):
        if self.Operation.text().strip() != "":
            self.Operation.setText("-("+(self.Operation.text())+")")

    def func_Delete(self):
        self.Operation.setText(self.Operation.text()[:-1])

    def func_Divide(self):
        self.Operation.setText(self.Operation.text()+"/")

    def func_One(self):
        self.Operation.setText(self.Operation.text()+"1")

    def func_Two(self):
        self.Operation.setText(self.Operation.text()+"2")

    def func_Three(self):
        self.Operation.setText(self.Operation.text()+"3")

    def func_Four(self):
        self.Operation.setText(self.Operation.text()+"4")

    def func_Five(self):
        self.Operation.setText(self.Operation.text()+"5")

    def func_Six(self):
        self.Operation.setText(self.Operation.text()+"6")

    def func_Seven(self):
        self.Operation.setText(self.Operation.text()+"7")

    def func_Eight(self):
        self.Operation.setText(self.Operation.text()+"8")

    def func_Nine(self):
        self.Operation.setText(self.Operation.text()+"9")

    def func_Zero(self):
        self.Operation.setText(self.Operation.text()+"0")

    def func_Point(self):
        self.Operation.setText(self.Operation.text()+".")

    def func_More(self):
        if self.More.text() == "More":
            self.Cos.show()
            self.Sin.show()
            self.Tan.show()
            self.Exp.show()
            self.Exponent.show()
            self.Euler.show()
            self.Pi.show()
            self.Ln.show()
            self.More.setText("Less")
        else:
            self.Cos.hide()
            self.Sin.hide()
            self.Tan.hide()
            self.Exp.hide()
            self.Exponent.hide()
            self.Euler.hide()
            self.Pi.hide()
            self.Ln.hide()
            self.More.setText("More")


    def func_Add(self):
        self.Operation.setText(self.Operation.text()+"+")

    def func_Multiply(self):
        self.Operation.setText(self.Operation.text()+"*")

    def func_Substract(self):
        self.Operation.setText(self.Operation.text()+"-")
    def func_Cos(self):
        self.Operation.setText(self.Operation.text()+"cos")


    def func_Sin(self):
        self.Operation.setText(self.Operation.text()+"sin")


    def func_Tan(self):
        self.Operation.setText(self.Operation.text()+"tan")


    def func_Ln(self):
        self.Operation.setText(self.Operation.text()+"log")


    def func_Exp(self):
        self.Operation.setText(self.Operation.text()+"exp")


    def func_Exponent(self):
        self.Operation.setText(self.Operation.text()+"**")


    def func_Euler(self):
        self.Operation.setText(self.Operation.text()+"e")


    def func_Pi(self):
        self.Operation.setText(self.Operation.text()+"pi")




    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Calculator"))
        self.Evaluate.setText(_translate("Frame", "="))
        self.Divide.setText(_translate("Frame", "/"))
        self.Clear.setText(_translate("Frame", "C"))
        self.Multiply.setText(_translate("Frame", "*"))
        self.Nine.setText(_translate("Frame", "9"))
        self.Exp.setText(_translate("Frame", "exp"))
        self.Six.setText(_translate("Frame", "6"))
        self.Sign.setText(_translate("Frame", "+/-"))
        self.Substract.setText(_translate("Frame", "-"))
        self.Delete.setText(_translate("Frame", "del"))
        self.Seven.setText(_translate("Frame", "7"))
        self.Sin.setText(_translate("Frame", "sin"))
        self.Eight.setText(_translate("Frame", "8"))
        self.Two.setText(_translate("Frame", "2"))
        self.Three.setText(_translate("Frame", "3"))
        self.Five.setText(_translate("Frame", "5"))
        self.Add.setText(_translate("Frame", "+"))
        self.Four.setText(_translate("Frame", "4"))
        self.Tan.setText(_translate("Frame", "tan"))
        self.Cos.setText(_translate("Frame", "cos"))
        self.One.setText(_translate("Frame", "1"))
        self.Ln.setText(_translate("Frame", "ln"))
        self.Euler.setText(_translate("Frame", "e"))
        self.Pi.setText(_translate("Frame", "pi"))
        self.Exponent.setText(_translate("Frame", "^"))
        self.Zero.setText(_translate("Frame", "0"))
        self.Point.setText(_translate("Frame", "."))
        self.More.setText(_translate("Frame", "More"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QMainWindow()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
